name: "Telebirr USSD"

on:
    push:
        branches: ["feature/*", "main", "bugfix/**"]
    pull_request:
        branches: ["main"]

jobs:
    telebirr-ussd-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                  php-version: "8.1"
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Execute tests (Unit and Feature tests) via PHPUnit
              env:
                  DB_CONNECTION: sqlite
                  DB_DATABASE: database/database.sqlite
              run: vendor/bin/phpunit tests
